# ============================================================================
#  ساخت فایل EXE ویندوز «لیستیا»
#  اجرا روی ویندوز:
#     powershell -ExecutionPolicy Bypass -File build_windows\build.ps1
#  با آدرس دلخواه اپ (پخت داخل EXE):
#     powershell -ExecutionPolicy Bypass -File build_windows\build.ps1 -AppUrl "https://example.chbk.app"
# ============================================================================
param(
    [string]$Python = "",      # مسیر دلخواه python.exe (اختیاری)
    [string]$AppUrl = ""       # آدرس وب‌اپ چابکان که داخل EXE پخت می‌شود (اختیاری)
)

$ErrorActionPreference = "Stop"

$Root   = Split-Path -Parent $PSScriptRoot
$Venv   = Join-Path $Root ".venv-build"
$Icon   = Join-Path $PSScriptRoot "icon\Listia.ico"
$VerFile = Join-Path $PSScriptRoot "version_info.txt"
$Dist   = Join-Path $Root "dist"
$SiteConfig = Join-Path $Root "desktop_siteconfig.py"

Set-Location $Root

function Resolve-PythonExe {
    if ($Python) {
        if (Test-Path $Python) { return (Resolve-Path $Python).Path }
        $cmd = Get-Command $Python -ErrorAction SilentlyContinue
        if ($cmd) { return $cmd.Source }
        throw "پایتون وارد شده پیدا نشد: $Python"
    }
    $cmd = Get-Command python -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Source }
    $py = Get-Command py -ErrorAction SilentlyContinue
    if ($py) { return $py.Source }
    throw "Python روی این سیستم پیدا نشد. لطفاً از python.org نسخه 3.10 تا 3.13 را نصب کنید و تیک 'Add to PATH' را بزنید."
}

$Py = Resolve-PythonExe
Write-Host "==> Python: $Py"
& $Py --version

# 1) ساخت محیط مجازی (در صورت نیاز)
if (-not (Test-Path (Join-Path $Venv "Scripts\python.exe"))) {
    Write-Host "==> ساخت محیط مجازی در $Venv"
    & $Py -m venv $Venv
}
$VenvPy = Join-Path $Venv "Scripts\python.exe"

Write-Host "==> نصب وابستگی‌های ساخت (pywebview + pythonnet + pyinstaller)"
& $VenvPy -m pip install --upgrade pip
& $VenvPy -m pip install -r (Join-Path $PSScriptRoot "requirements.txt")

# 2) پخت آدرس اپ داخل EXE (اختیاری)
if ($AppUrl) {
    $url = $AppUrl.Trim().TrimEnd('/')
    Write-Host "==> پخت آدرس اپ داخل EXE: $url"
    Set-Content -Path $SiteConfig -Value "# generated by build.ps1`nAPP_URL = '$url'`n" -Encoding UTF8
} elseif (Test-Path $SiteConfig) {
    Remove-Item $SiteConfig -Force
}

# 3) ساخت EXE یک‌فایلی
Write-Host "==> ساخت EXE با PyInstaller (یک فایل، بدون پنجره کنسول)"
$pyinstallerArgs = @(
    "--noconfirm", "--clean", "--onefile", "--windowed",
    "--name", "Listia",
    "--icon", $Icon,
    "--version-file", $VerFile,
    "--add-data", "$Icon;desktop_assets",
    "--hidden-import", "clr",
    "--hidden-import", "clr_loader",
    "desktop_launcher.py"
)
& $VenvPy -m PyInstaller @pyinstallerArgs
if ($LASTEXITCODE -ne 0) { throw "PyInstaller با خطا متوقف شد." }

# 4) پاک‌سازی فایل موقت پیکربندی آدرس (تا داخل مخزن نماند)
if (Test-Path $SiteConfig) { Remove-Item $SiteConfig -Force }

Write-Host ""
Write-Host "=============================================================="
Write-Host "  ساخته شد: $Dist\Listia.exe"
Write-Host "=============================================================="
Write-Host "نکته: می‌توانید فایل .env را کنار Listia.exe بگذارید تا آدرس اپ"
Write-Host "      (LISTIA_APP_URL) یا عنوان پنجره (LISTIA_TITLE) را عوض کنید."
